export const products = [
    
    {
      id: 13,
      name: "anime character bag",
      category: "anime bag",
      price: 25000000,
      image: "/images/anime.jpg",
      isCart: false,
      description: "tas karakter anime berkualitas",
    },
    {
      id: 14,
      name: "BOBOIBOY CHARACTER BAG",
      category: "character bag",
      price: 30000000,
      image: "/images/boboiboy.jpg",
      isCart: false,
      description: "Tas dengan karakter boboiboy",
    },
    {
      id: 15,
      name: "HELLO KITTY CHARACTER BAG",
      category: "character bag",
      price: 20000000,
      image: "/images/hellokt.jpg",
      isCart: false,
      description: "TAS DENGAN KARAKTER HELOKITTY",
    },
    {
      id: 16,
      name: "MICKEY MOUSE CHARACTER BAG",
      category: "character bag",
      price: 26000000,
      image: "/images/mikimos.jpg",
      isCart: false,
      description: "Garansi jaminan pngiriman aman sampai tujuan",
    },
    {
      id: 17,
      name: "THOMAS CHARACTER BAG",
      category: "character bag",
      price: 31000000,
      image: "/images/tomas.jpg",
      isCart: false,
      description: "TAS DENGAN KARAKTER THOMAS",
    },
    {
      id: 18,
      name: "DORAEMON CHARACTER SUITCASE",
      category: "character suitcase",
      price: 35000000,
      image: "/images/doraemon.jpg",
      isCart: false,
      description: "TAS DENGAN KARAKTER DORAEMON",
    },
  
    {
      id: 19,
      name: "character bag",
      category: "character bag",
      price: 40000000,
      image: "/images/characterbag.jpg",
      isCart: false,
      description: "tas kualitas terbaik",
    },
    
  ];