export const products = [
    {
      id: 1,
      name: "SAPI JAWA COKLAT",
      category: "SAPI JAWA",
      price: 20000000,
      image: "/images/product1.jpg",
      isCart: false,
      description: "Sapi asli dari peternakan Indonesia yaitu wilayah tanah Jawa.Kondisi sehat terjamin.Badan besar dan terawat dengan jaminan daging yang segar.Asli dipelihara dari peternak berpengalaman.Garansi jaminan pngiriman aman sampai tujuan",
    },
    {
      id: 2,
      name: "SAPI LEMOSIN COKLAT",
      category: "SAPI LEMOSIN",
      price: 25000000,
      image: "/images/product11.jpg",
      isCart: false,
      description: "Sapi asli dari peternakan Swiss.Kondisi sehat terjamin.Badan besar dan terawat dengan jaminan daging yang segar.Asli dipelihara dari peternak berpengalaman.Garansi jaminan pngiriman aman sampai tujuan",
    },
    {
      id: 3,
      name: "SAPI METAL PUTIH",
      category: "SAPI METAL",
      price: 30000000,
      image: "/images/product3.jpg",
      isCart: false,
      description: "Sapi asli dari peternakan Indonesia dan Swiss.Kondisi sehat terjamin.Badan besar dan terawat dengan jaminan daging yang segar.Asli dipelihara dari peternak berpengalaman.Garansi jaminan pngiriman aman sampai tujuan",
    },
    {
      id: 4,
      name: "SAPI JAWA PUTIH",
      category: "SAPI JAWA",
      price: 20000000,
      image: "/images/jwap2.jpg",
      isCart: false,
      description: "Sapi asli dari peternakan Indonesia yaitu wilayah tanah Jawa.Kondisi sehat terjamin.Badan besar dan terawat dengan jaminan daging yang segar.Asli dipelihara dari peternak berpengalaman.Garansi jaminan pngiriman aman sampai tujuan",
    },
    {
      id: 5,
      name: "SAPI LEMOSIN PUTIH",
      category: "SAPI LEMOSIN",
      price: 26000000,
      image: "/images/lemop2.jpg",
      isCart: false,
      description: "Sapi asli dari peternakan Swiss.Kondisi sehat terjamin.Badan besar dan terawat dengan jaminan daging yang segar.Asli dipelihara dari peternak berpengalaman.Garansi jaminan pngiriman aman sampai tujuan",
    },
    {
      id: 6,
      name: "SAPI METAL HITAM",
      category: "SAPI METAL",
      price: 31000000,
      image: "/images/mtlh2.jpg",
      isCart: false,
      description: "Sapi asli dari peternakan Indonesia dan Swiss.Kondisi sehat terjamin.Badan besar dan terawat dengan jaminan daging yang segar.Asli dipelihara dari peternak berpengalaman.Garansi jaminan pngiriman aman sampai tujuan",
    },
    {
      id: 7,
      name: "SAPI METAL POLKADOT",
      category: "SAPI METAL",
      price: 35000000,
      image: "/images/mtplk.jpg",
      isCart: false,
      description: "Sapi asli dari peternakan Indonesia dan Swiss.Kondisi sehat terjamin.Badan besar dan terawat dengan jaminan daging yang segar.Asli dipelihara dari peternak berpengalaman.Garansi jaminan pngiriman aman sampai tujuan",
    },
    {
      id: 8,
      name: "SAPI JAWA POLKADOT",
      category: "SAPI JAWA",
      price: 35000000,
      image: "/images/jwht.jpg",
      isCart: false,
      description: "Sapi asli dari peternakan Indonesia yaitu wilayah tanah Jawa.Kondisi sehat terjamin.Badan besar dan terawat dengan jaminan daging yang segar.Asli dipelihara dari peternak berpengalaman.Garansi jaminan pngiriman aman sampai tujuan",
    },
    {
      id: 9,
      name: "KERBAU HITAM",
      category: "KERBAU LOKAL",
      price: 35000000,
      image: "/images/kerh.jpg",
      isCart: false,
      description: "Kerbau asli dari peternakan Indonesia yaitu wilayah tanah Jawa.Kondisi sehat terjamin.Badan besar dan terawat dengan jaminan daging yang segar.Asli dipelihara dari peternak berpengalaman.Garansi jaminan pngiriman aman sampai tujuan",
    },
    {
      id: 10,
      name: "KERBAU ALBINO PUTIH",
      category: "KERBAU ALBINO",
      price: 39000000,
      image: "/images/kerp.jpeg",
      isCart: false,
      description: "Kerbau asli dari peternakan Swiss.Kondisi sehat terjamin.Badan besar dan terawat dengan jaminan daging yang segar.Asli dipelihara dari peternak berpengalaman.Garansi jaminan pngiriman aman sampai tujuan",
    },
    {
      id: 11,
      name: "KERBAU COKLAT",
      category: "KERBAU LOKAL",
      price: 35000000,
      image: "/images/kercok.jpg",
      isCart: false,
      description: "Sapi asli dari peternakan Indonesia yaitu wilayah tanah Jawa.Kondisi sehat terjamin.Badan besar dan terawat dengan jaminan daging yang segar.Asli dipelihara dari peternak berpengalaman.Garansi jaminan pngiriman aman sampai tujuan",
    },
    {
      id: 12,
      name: "KERBAU ALBINO POLKADOT",
      category: "KERBAU ALBINO",
      price: 40000000,
      image: "/images/kerpol.jpg",
      isCart: false,
      description: "Kerbau asli dari peternakan Swiss.Kondisi sehat terjamin.Badan besar dan terawat dengan jaminan daging yang segar.Asli dipelihara dari peternak berpengalaman.Garansi jaminan pngiriman aman sampai tujuan",
    },
    
  ];